### ISSUE TITLE
Create a ROCK for kserve/paddleserver v0.11

### ISSUE THREAD

**Issue by misohu** [canonical/kserve-rocks#18]
### Context

Create ROCK based on [upstream Dockerfile](https://github.com/kserve/kserve/blob/release-0.11/python/paddle.Dockerfile). You can take the inspiration from pmml server ROCK in main branch. Don't forget to use [ROCK's entrypoint service](https://canonical-rockcraft.readthedocs-hosted.com/en/latest/reference/rockcraft.yaml/#entrypoint-service) to correctly pass the arguments to workload container.

### What needs to get done

1. Create ROCK 
2. Manually push the ROCK to Dockerhub

### Definition of Done

1. ROCK code is ready
2. ROCK is available at Dockerhub

**Comment by ca-scribner** [comment]
#20 implemented an attempt at this, but integration testing with kserve found the image published as `charmedkubeflow/paddleserver:0.11.0-a7478be` was missing libgomp1 in the final rock (it was mistakenly taken as a build dependency, not a runtime dependency).

**Comment by ca-scribner** [comment]
Closing this as we did implement something, but we're now blocked by [this issue](https://github.com/canonical/kserve-rocks/issues/28) which will be addressed separately.
