### ISSUE TITLE
Create a ROCK for kserve/sklearnserver v0.11

### ISSUE THREAD

**Issue by misohu** [canonical/kserve-rocks#19]
### Context

Create ROCK based on [upstream Dockerfile](https://github.com/kserve/kserve/blob/release-0.11/python/sklearn.Dockerfile). You can take the inspiration from pmml server ROCK in main branch. Don't forget to use [ROCK's entrypoint service](https://canonical-rockcraft.readthedocs-hosted.com/en/latest/reference/rockcraft.yaml/#entrypoint-service) to correctly pass the arguments to workload container.

### What needs to get done

1. Create ROCK 
2. Manually push the ROCK to Dockerhub

### Definition of Done

1. ROCK code is ready
2. ROCK is available at Dockerhub

**Comment by ca-scribner** [comment]
closed by #23
